mixed-port: 4949
mode: rule
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:4953
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 22.49.0.1/16
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - 223.6.6.6
    - 119.29.29.29
    - 180.184.2.2
    - 114.114.115.115
    - 1.2.4.8
