mixed-port: 4949
mode: rule
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:4953
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - 223.6.6.6
    - 119.29.29.29
